### ISSUE TITLE
video-embedding question (shameless)

### ISSUE THREAD

**Issue by ijlyttle** [ijlyttle/user2016_knitr#1]
Hi @yihui,

This is a little bit off the defined path, so not urgent. 

If and when you have time, could you look at this file?

https://github.com/ijlyttle/user2016_knitr/blob/master/ian_sandbox/shameless.Rmd

The basic question is to see if there is a knitr-friendly way to center html embeds.

Thanks,

Ian

**Comment by yihui** [comment]
I think `tags$div(align = 'center')` is a reasonable approach.

Another approach is to use CSS to center all `iframe`'s. This may be a better example for P13 in the slides: https://dl.dropboxusercontent.com/u/15335397/slides/2016-useR-rmarkdown-Yihui-Xie.html#(13)

``` css
iframe {
  display: block;
  margin: auto;
}
```

**Comment by ijlyttle** [comment]
Thanks!
